name: CI-CD Pipeline for Practice GitHub Action

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: My First Step
        run: |
          echo "This is devops practice"
          uname -a
      - name: Check docker installation
        run: |
          docker
          docker images
      - name: Run docker container
        run: |
          docker run hello-world
